spring:
  application:
    name: qeaa-issuer
  output:
    ansi:
      enabled: ALWAYS
server:
  forward-headers-strategy: framework
springdoc:
  cache:
   disabled: true
  packages-to-scan:
  - it.ipzs.qeaaissuer.controller
  paths-to-exclude:
  - /cie/**
auth-controller:
  redirect-url: https://api.eudi-wallet-it-issuer.it/request_uri
  client-url: https://api.eudi-wallet-it-issuer.it
consent-controller:
  consent-url: https://api.eudi-wallet-it-issuer.it/cie/consent
  accepted-url: https://api.eudi-wallet-it-issuer.it/cie/accepted
  callback-url: https://api.eudi-wallet-it-issuer.it/callback
logging:
  level:
    '[it.ipzs.qeaaissuer.controller.AuthController]': WARN
keys:
  directory-path: ${user.home}/key
  path: ${keys.directory-path}/eudi-pp-key-jwk.json
  public-jwk-set-path: ${keys.directory-path}/eudi-pp-public-jwk.json
  encr-path: ${keys.directory-path}/eudi-encr-rp-key-jwk.json
  public-encr-jwk-set-path: ${keys.directory-path}/eudi-encr-rp-public-key-jwk.json
oidc:
   hosts:
      trust-anchor: 127.0.0.1
      cie-provider: 127.0.0.1
      relying-party: 127.0.0.1

      
   # required for onboarding checks and also for all the leafs
   default-trust-anchor: "http://${oidc.hosts.trust-anchor}:8000/"

   federation-trust-chain-url: "https://demo.federation.eudi.wallet.developers.italia.it/fetch?sub=https://api.eudi-wallet-it-issuer.it/rp/"

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "EUDI Wallet IT Issuer"
      application-type: "web"
      contacts:
      - "ipzssviluppo@gmail.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: 
      - private_key_jwt
      client-id: "http://${oidc.hosts.relying-party}:8080/rp"
      redirect-uris:
      - "http://${oidc.hosts.relying-party}:8080/callback"
      request-uris:
      - "http://${oidc.hosts.relying-party}:8080/request_uri"
      jwk-file-path: ${user.home}/oidc-rp-jwk.json
      trust-marks-file-path: ${user.home}/oidc-rp-trust-marks.json
      encr-jwk-file-path: ${user.home}/key/eudi-encr-rp-key-jwk.json      

   openid-credential-issuer:
      credential-issuer: 127.0.0.1:8080
      id: eudi-wallet-it-issuer.it
      dpop-signing-alg-values-supported:
      - RS256
      authorization-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/authorize"
      token-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/token"
      pushed-authorization-request-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/as/par"
      credential-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/credential"
      jwk-file-path: ${user.home}/key/eudi-pp-key-jwk.json
      sub: "http://${oidc.hosts.relying-party}:8080/ci"
   federation-entity:
     homepage-uri: "http://${oidc.hosts.relying-party}:8080/rp"
     organization-name: "EUDI IT Wallet Issuer"
     policy-uri: "http://${oidc.hosts.relying-party}:8080/rp"
     tos-uri: "http://${oidc.hosts.relying-party}:8080/rp"
     logo-uri:  "http://${oidc.hosts.relying-party}:8080/public/logo.svg"
     
metadata:
  path: ${user.home}/metadata.json
