server:
  port: 8443
auth-controller:
  redirect-url: http://localhost:8080/request_uri
consent-controller:
  consent-url: http://localhost:8080/cie/consent
  accepted-url: http://localhost:8080/cie/accepted
  callback-url: http://localhost:8080/callback
logging:
  level:
    '[it.ipzs.qeaaissuer.controller.AuthController]': WARN
oidc:
   hosts:
      trust-anchor: 127.0.0.1
      cie-provider: 127.0.0.1
      relying-party: 127.0.0.1

      
   # required for onboarding checks and also for all the leafs
   default-trust-anchor: "http://${oidc.hosts.trust-anchor}:8000/"

   federation-trust-chain-url: "https://demo.federation.eudi.wallet.developers.italia.it/fetch?sub=https://api.eudi-wallet-it-issuer.it/rp/"

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "EUDI Wallet IT Issuer"
      application-type: "web"
      contacts:
      - "ipzssviluppo@gmail.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: 
      - private_key_jwt
      client-id: "http://${oidc.hosts.relying-party}:${server.port}/rp"
      redirect-uris:
      - "http://${oidc.hosts.relying-party}:${server.port}/callback"
      request-uris:
      - "http://${oidc.hosts.relying-party}:${server.port}/request_uri"
      jwk-file-path: ${user.home}/oidc-rp-jwk.json
      trust-marks-file-path: ${user.home}/oidc-rp-trust-marks.json
      encr-jwk-file-path: ${user.home}/key/eudi-encr-rp-key-jwk.json      

   openid-credential-issuer:
      credential-issuer: 127.0.0.1:${server.port}
      id: europeandisabilitycard.eudi-wallet-it-issuer.it
      dpop-signing-alg-values-supported:
      - RS256
      authorization-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/authorize"
      token-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/token"
      pushed-authorization-request-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/as/par"
      credential-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/credential"
      jwk-file-path: ${user.home}/key/eudi-pp-key-jwk.json
      sub: "http://${oidc.hosts.relying-party}:${server.port}/ci"
   federation-entity:
     homepage-uri: "http://${oidc.hosts.relying-party}:${server.port}/rp"
     organization-name: "EUDI IT Wallet Issuer"
     policy-uri: "http://${oidc.hosts.relying-party}:${server.port}/rp"
     tos-uri: "http://${oidc.hosts.relying-party}:${server.port}/rp"
     logo-uri:  "http://${oidc.hosts.relying-party}:${server.port}/public/logo.svg"