spring:
  application:
    name: it-pid-provider
  output:
    ansi:
      enabled: ALWAYS
server:
  forward-headers-strategy: framework
springdoc:
  cache:
   disabled: true
  packages-to-scan:
  - it.ipzs.pidprovider.controller
  paths-to-exclude:
  - /cie/**
auth-controller:
  redirect-url: https://api.eudi-wallet-it-pid-provider.it/cie/login
consent-controller:
  consent-url: https://api.eudi-wallet-it-pid-provider.it/cie/consent
  accepted-url: https://api.eudi-wallet-it-pid-provider.it/cie/accepted
  callback-url: https://api.eudi-wallet-it-pid-provider.it/callback
