auth-controller:
  redirect-url: http://localhost:8080/cie/login
consent-controller:
  consent-url: http://localhost:8080/cie/consent
  accepted-url: http://localhost:8080/cie/accepted
  callback-url: http://localhost:8080/callback
logging:
  level:
    '[it.ipzs.qeeaissuer.controller.AuthController]': WARN