spring:
  application:
    name: it-pid-provider
  output:
    ansi:
      enabled: ALWAYS
server:
  forward-headers-strategy: framework
  max-http-request-header-size: 3MB
  port: ${SERVER_PORT}
springdoc:
  cache:
   disabled: true
  packages-to-scan:
  - it.ipzs.pidprovider.controller
  paths-to-exclude:
  - /cie/**
base-url: ${BASE_URL}
auth-controller:
  redirect-url: ${BASE_URL}/callback
  issuer-url: ${BASE_URL}
consent-controller:
  consent-url: ${BASE_URL}/cie/consent
  accepted-url: ${BASE_URL}/cie/accepted
  callback-url: ${BASE_URL}/callback
logging:
  level:
    '[it.ipzs.pidprovider.controller.AuthController]': WARN
keys:
  directory-path: ${KEY_ROOT_PATH}
  path: ${keys.directory-path}/eudi-pp-key-jwk.json
  public-jwk-set-path: ${keys.directory-path}/eudi-pp-public-jwk.json
  encr-path: ${keys.directory-path}/eudi-encr-pp-key-jwk.json
  public-encr-jwk-set-path: ${keys.directory-path}/eudi-encr-pp-public-key-jwk.json
oidc:
   hosts:
      trust-anchor: ${HOST_TRUST_ANCHOR}
      cie-provider: ${HOST_CIE_PROVIDER}
      relying-party: ${HOST_RELYING_PARTY}

   # required for onboarding checks and also for all the leafs
   default-trust-anchor: ${DEFAULT_TRUST_ANCHOR}
   
   federation-trust-chain-url: ${FEDERATION_TC_URL}

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "EUDI Wallet IT PID Provider"
      application-type: "web"
      contacts:
      - "ipzssviluppo@gmail.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: 
      - private_key_jwt
      client-id: ${RP_CLIENT_ID}
      redirect-uris:
      - ${RP_REDIRECT_CALLBACK_URI}
      jwk-file-path: ${RP_JWK_FILE_PATH}
      trust-marks-file-path: ${RP_TRUST_MARK_FILE_PATH}

   openid-credential-issuer:
      credential-issuer: ${OID_CI_CRED_ISS}
      dpop-signing-alg-values-supported:
      - RS256
      authorization-endpoint: "${oidc.openid-credential-issuer.credential-issuer}/authorize"
      token-endpoint: "${oidc.openid-credential-issuer.credential-issuer}/token"
      pushed-authorization-request-endpoint: "${oidc.openid-credential-issuer.credential-issuer}/as/par"
      credential-endpoint: "${oidc.openid-credential-issuer.credential-issuer}/credential"
      jwk-file-path: ${OID_CI_JWK_FILE_PATH}
      encr-jwk-file-path: ${OID_CI_ENCR_JWK_FILE_PATH}
      sub: "${oidc.openid-credential-issuer.credential-issuer}/ci"

   federation-entity:
     homepage-uri: "http://${oidc.hosts.relying-party}/rp"
     organization-name: "EUDI IT Wallet Pid Provider"
     policy-uri: "http://${oidc.hosts.relying-party}/rp"
     tos-uri: "http://${oidc.hosts.relying-party}/rp"
     logo-uri:  "http://${oidc.hosts.relying-party}/public/logo.svg"
