spring:
  application:
    name: it-pid-provider
  output:
    ansi:
      enabled: ALWAYS
server:
  forward-headers-strategy: framework
springdoc:
  cache:
   disabled: true
  packages-to-scan:
  - it.ipzs.pidprovider.controller
  paths-to-exclude:
  - /cie/**
base-url: api.eudi-wallet-it-pid-provider.it
auth-controller: 
  redirect-url: https://${base-url}/callback
  issuer-url: https://${base-url}
consent-controller:
  consent-url: https://${base-url}/cie/consent
  accepted-url: https://${base-url}/cie/accepted
  callback-url: https://${base-url}/callback
logging:
  level:
    '[it.ipzs.pidprovider.controller.AuthController]': WARN
keys:
  directory-path: ${user.home}/key
  path: ${keys.directory-path}/eudi-pp-key-jwk.json
  public-jwk-set-path: ${keys.directory-path}/eudi-pp-public-jwk.json
  encr-path: ${keys.directory-path}/eudi-encr-key-jwk.json
  public-encr-jwk-set-path: ${keys.directory-path}/eudi-encr-public-key-jwk.json
oidc:
   hosts:
      trust-anchor: 127.0.0.1
      cie-provider: 127.0.0.1
      relying-party: ${base-url}

      
   # required for onboarding checks and also for all the leafs
   default-trust-anchor: "http://${oidc.hosts.trust-anchor}:8000/"
   
   federation-trust-chain-url: "https://demo.federation.eudi.wallet.developers.italia.it/fetch?sub=https://${base-url}/ci"

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "SpringBoot RP Sample"
      application-type: "web"
      contacts:
      - "dev@example.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: 
      - private_key_jwt
      client-id: "http://${oidc.hosts.relying-party}/ci"
      redirect-uris:
      - "http://${oidc.hosts.relying-party}/callback"
      jwk-file-path: ${user.home}/oidc-rp-jwk.json
      trust-marks-file-path: ${user.home}/oidc-rp-trust-marks.json

   openid-credential-issuer:
      credential-issuer: ${base-url}
      dpop-signing-alg-values-supported:
      - RS256
      authorization-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/authorize"
      token-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/token"
      pushed-authorization-request-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/as/par"
      credential-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/credential"
      jwk-file-path: ${user.home}/key/eudi-pp-key-jwk.json
      encr-jwk-file-path: ${user.home}/key/eudi-encr-key-jwk.json
      sub: "http://${oidc.hosts.relying-party}/ci"

   federation-entity:
     homepage-uri: "http://${oidc.hosts.relying-party}/ci"
     organization-name: "EUDI IT Wallet Pid Provider"
     policy-uri: "http://${oidc.hosts.relying-party}/ci"
     tos-uri: "http://${oidc.hosts.relying-party}/ci"
     logo-uri:  "http://${oidc.hosts.relying-party}/public/logo.svg"
metadata:
  path: ${user.home}/metadata.json
