spring:
  application:
    name: qeaa-issuer
  output:
    ansi:
      enabled: ALWAYS
server:
  forward-headers-strategy: framework
springdoc:
  cache:
   disabled: true
  packages-to-scan:
  - it.ipzs.qeaaissuer.controller
  paths-to-exclude:
  - /cie/**
base-url: api.eudi-wallet-it-issuer.it
auth-controller:
  redirect-url: https://${base-url}/request_uri
  client-url: https://${base-url}
consent-controller:
  consent-url: https://${base-url}/cie/consent
  accepted-url: https://${base-url}/cie/accepted
  callback-url: https://${base-url}/callback
vp-token:
  aud-uri: https://${base-url}/callback
logging:
  level:
    '[it.ipzs.qeaaissuer.controller.AuthController]': WARN
keys:
  directory-path: ${user.home}/key
  path: ${keys.directory-path}/eudi-pp-key-jwk.json
  public-jwk-set-path: ${keys.directory-path}/eudi-pp-public-jwk.json
  mdoc-path: ${keys.directory-path}/eudi-pp-mdoc-key-jwk.json
  mdoc-public-path: ${keys.directory-path}/eudi-pp-mdoc-public-key-jwk.json
  encr-path: ${keys.directory-path}/eudi-encr-rp-key-jwk.json
  public-encr-jwk-set-path: ${keys.directory-path}/eudi-encr-rp-public-key-jwk.json
  x5c-path: ${keys.directory-path}/x5c.txt
  x5c-url: http://localhost:8080/api/certificates #for testing purpose, ref to CA
pid-provider: #pid provider ES
  url: https://api.eudi-wallet-it-pid-provider.it/ci/.well-known/openid-federation?format=json
edc-service:
  url: http://localhost:9898/client/get/ 
oidc:
   hosts:
      trust-anchor: 127.0.0.1
      cie-provider: 127.0.0.1
      relying-party: ${base-url}

      
   # required for onboarding checks and also for all the leafs
   default-trust-anchor: "http://${oidc.hosts.trust-anchor}:8000/"

   federation-trust-chain-url: "https://demo.federation.eudi.wallet.developers.italia.it/fetch?sub=https://${base-url}/rp/"

   # List of trust anchors
   trust-anchors:
   - ${oidc.default-trust-anchor}

   # Map of known OPs and related Trust Anchor.
   spid-providers:
     - subject: "http://${oidc.hosts.trust-anchor}:8000/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}
   cie-providers:
     - subject: "http://${oidc.hosts.cie-provider}:8002/oidc/op/"
       trust-anchor: ${oidc.default-trust-anchor}

   relying-party:
      application-name: "EUDI Wallet IT Issuer"
      application-type: "web"
      contacts:
      - "ipzssviluppo@gmail.com"
      #response-types  only "code" allowed
      scope:
      - openid
      - offline_access
      token-endpoint-auth-method: 
      - private_key_jwt
      client-id: "http://${oidc.hosts.relying-party}/rp"
      redirect-uris:
      - "http://${oidc.hosts.relying-party}/callback"
      request-uris:
      - "http://${oidc.hosts.relying-party}/request_uri"
      jwk-file-path: ${user.home}/oidc-rp-jwk.json
      trust-marks-file-path: ${user.home}/oidc-rp-trust-marks.json
      encr-jwk-file-path: ${user.home}/key/eudi-encr-rp-key-jwk.json      

   openid-credential-issuer:
      credential-issuer: ${base-url}
      id: eudi-wallet-it-issuer.it
      dpop-signing-alg-values-supported:
      - RS256
      authorization-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/authorize"
      token-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/token"
      pushed-authorization-request-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/as/par"
      credential-endpoint: "http://${oidc.openid-credential-issuer.credential-issuer}/credential"
      jwk-file-path: ${user.home}/key/eudi-pp-key-jwk.json
      sub: "http://${oidc.hosts.relying-party}/ci"
      mdoc-jwk-file-path: ${user.home}/key/eudi-pp-mdoc-key-jwk.json
      x5c-path: ${keys.directory-path}/x5c.txt
   federation-entity:
     homepage-uri: "http://${oidc.hosts.relying-party}/rp"
     organization-name: "Istituto Poligrafico e Zecca dello Stato"
     policy-uri: "http://${oidc.hosts.relying-party}/rp"
     tos-uri: "http://${oidc.hosts.relying-party}/rp"
     logo-uri:  "http://${oidc.hosts.relying-party}/public/logo.svg"
